<?php
	$clientName = "CLIENT_NAME_GOES_HERE";
	$testURL = "URL_TO_TEST_GOES_HERE";
	$needle = "KEYWORD_TO_CONFIRM_VALID_TEST_GOES_HERE";
	$textBeltAPIKey = "TEXTBELT_API_KEY_GOES_HERE";
	$recipientPhone = "RECIPIENT_PHONE_NUMBER_GOES_HERE";
?>